//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letsvote.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRecord
    {
        public int Admin_id { get; set; }
        public string password { get; set; }
        public string name { get; set; }
    }
}
