//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letsvote.DataAccess
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class voter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voter()
        {
            this.votes = new HashSet<vote>();
        }
    
        public int voter_id { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string address { get; set; }
        public string password { get; set; }
        [JsonIgnore]
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vote> votes { get; set; }
    }
}
