//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letsvote.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vote
    {
        public int Voter_id { get; set; }
        public int Party_id { get; set; }
        public int vote_id { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual voter voter { get; set; }
    }
}
